[params]
  primaryBackgroundImage = "https://i.pinimg.com/736x/6c/ab/cc/6cabccf7f0ebb599cb4fd1dd783877dd.jpg"
  secondaryBackgroundImage = "https://i.pinimg.com/736x/6c/ab/cc/6cabccf7f0ebb599cb4fd1dd783877dd.jpg"
  backgroundImage = "https://i.pinimg.com/736x/6c/ab/cc/6cabccf7f0ebb599cb4fd1dd783877dd.jpg"
